name: ncRNAHD
channels:
  - pytorch
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.12
  - pytorch
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyter
  - faiss-cpu
  - pip
  - pip:
      - biopython
      - einops
      - ncrnabert
      - rotary-embedding-torch
      - sympy
